name: CICD_Pipeline

on:
  push:
  pull_request:


jobs:
  pylint_check:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"] 
        
    steps:

    - uses: actions/checkout@v3 # Get code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py' | grep -v 'scripts/ccs.py')


  CCS_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./scripts/ccs.py

      - name: Execute
        id: ccs_check
        run: ./scripts/ccs.py

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment

      # - name: Create or update comment
      #   uses: peter-evans/create-or-update-comment@v4
      #   if: success()
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     github-token: ${{ secrets.MY_TOKEN }}
      #     body: "CCS Check Passed"


  


