name: CICD_Pipeline ##

on:
  push: ## Push 
  pull_request: ## PR


jobs:
  pylint_check: ## Pylint check
  
    runs-on: ubuntu-latest # Set up virtual environment
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"] # Specify python version
        
    steps:

    - uses: actions/checkout@v3 # Get code

    - name: Set up Python ${{ matrix.python-version }} # Set up python with versions in matrix
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies # Install & Upgrade
      run: | # Upgrade 'pip' to latest version, install all package in 'requirements.txt'
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        
    - name: Analysing the code with pylint # Analyze all file end with '.py', excluding ccs.py
      run: |
        pylint $(git ls-files '*.py' | grep -v 'scripts/ccs.py')

  CCS_check: ## CCS check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute CCS
        id: ccs
        run: |
          if ./scripts/ccs.py; then
            echo "CCS_SUCCESS=true" >> $GITHUB_ENV 
          else
            echo "CCS_SUCCESS=false" >> $GITHUB_ENV
          fi

      - name: Post result to PR if successful
        if: env.CCS_SUCCESS == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentBody = "### CCS Check Successful\n" + 
                                "CCS check completed successfully without errors.";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: commentBody
            });

