name: CICD_Pipeline

on: 
  pull_request: ## PR


jobs:
  pylint_check: ## Pylint check
  
    runs-on: ubuntu-latest # Set up virtual environment
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"] # Specify python version
        
    steps:

    - uses: actions/checkout@v3 # Get code

    - name: Set up Python ${{ matrix.python-version }} # Set up python with versions in matrix
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies # Install & Upgrade
      run: | # Upgrade 'pip' to latest version, install all package in 'requirements.txt'
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        
    - name: Analysing the code with pylint # Analyze all file end with '.py', excluding ccs.py
      run: |
        pylint $(git ls-files '*.py' | grep -v 'scripts/ccs.py') > pylint_output.txt || true

    - name: Post pylint Results to PR comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            const fs = require('fs');
            const ccsOutput = fs.readFileSync('pylint_output.txt', 'utf8');
            const commentBody = '### CCS Check Results\n```' + ccsOutput + '```';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: commentBody
            });

  CCS_check: ## CCS check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make script executable # Make it executable
        run: chmod +x ./scripts/ccs.py

      - name: Execute
        run: ./scripts/ccs.py


